### ISSUE TITLE
Error from your Plugin

### ISSUE THREAD

**Issue by ignoIT** [kasparsd/contact-form-7-extras#43] opened 2020-12-29 13:29 UTC
Deprecated: get_option wurde mit einem Parameter oder Argument aufgerufen, der seit Version 5.5.0 veraltet ist! Der OptionsschlÃ¼ssel â€žblacklist_keysâ€œ wurde in â€ždisallowed_keysâ€œ umbenannt. in /mnt/web017/a0/21/51204221/htdocs/******/wp-includes/functions.php on line 5143 Warning: Cannot modify header information - headers already sent by (output started at /mnt/web017/a0/21/51204221/htdocs/******/wp-includes/functions.php:5143) in /mnt/web017/a0/21/51204221/htdocs/******/wp-includes/pluggable.php on line 1296 Warning: Cannot modify header information - headers already sent by (output started at /mnt/web017/a0/21/51204221/htdocs/******/wp-includes/functions.php:5143) in /mnt/web017/a0/21/51204221/htdocs/******/wp-includes/pluggable.php on line 1299

**Comment by kasparsd** [comment] 2024-12-16 10:43
Closing as this was reported 4 years ago and I can't reproduce this while developing the plugin. Please comment if this can still be replicated.

**Closed by kasparsd** 2024-12-16 10:43 UTC
